package com.bookstore.utility;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WorldCountryConstants {


    public static final Map<String, String> mapOfWorldStates = new HashMap<String, String>() {

        {

            put("Andorra, Principality Of", "AD");
            put("United Arab Emirates", "AE");
            put("Afghanistan, Islamic State Of", "AF");
            put("Antigua And Barbuda", "AG");
            put("Anguilla", "AI");
            put("Albania", "AL");
            put("Armenia", "AM");
            put("Netherlands Antilles", "AN");
            put("Angola", "AO");
            put("Antarctica", "AQ");
            put("Argentina", "AR");
            put("American Samoa", "AS");
            put("Austria", "AT");
            put("Australia", "AU");
            put("Aruba", "AW");
            put("Azerbaidjan", "AZ");
            put("Bosnia-Herzegovina", "BA");
            put("Barbados", "BB");
            put("Bangladesh", "BD");
            put("Belgium", "BE");
            put("Burkina Faso", "BF");
            put("Bulgaria", "BG");
            put("Bahrain", "BH");
            put("Burundi", "BI");
            put("Benin", "BJ");
            put("Bermuda", "BM");
            put("Brunei Darussalam", "BN");
            put("Bolivia", "BO");
            put("Brazil", "BR");
            put("Bahamas", "BS");
            put("Bhutan", "BT");
            put("Bouvet Island", "BV");
            put("Botswana", "BW");
            put("Belarus", "BY");
            put("Belize", "BZ");
            put("Canada", "CA");
            put("Cocos (Keeling) Islands", "CC");
            put("Central African Republic", "CF");
            put("Congo, The Democratic Republic Of The", "CD");
            put("Congo", "CG");
            put("Switzerland", "CH");
            put("Ivory Coast (Cote D'Ivoire)", "CI");
            put("Cook Islands", "CK");
            put("Chile", "CL");
            put("Cameroon", "CM");
            put("China", "CN");
            put("Colombia", "CO");
            put("Costa Rica", "CR");
            put("Former Czechoslovakia", "CS");
            put("Cuba", "CU");
            put("Cape Verde", "CV");
            put("Christmas Island", "CX");
            put("Cyprus", "CY");
            put("Czech Republic", "CZ");
            put("Germany", "DE");
            put("Djibouti", "DJ");
            put("Denmark", "DK");
            put("Dominica", "DM");
            put("Dominican Republic", "DO");
            put("Algeria", "DZ");
            put("Ecuador", "EC");
            put("Estonia", "EE");
            put("Egypt", "EG");
            put("Western Sahara", "EH");
            put("Eritrea", "ER");
            put("Spain", "ES");
            put("Ethiopia", "ET");
            put("Finland", "FI");
            put("Fiji", "FJ");
            put("Falkland Islands", "FK");
            put("Micronesia", "FM");
            put("Faroe Islands", "FO");
            put("France", "FR");
            put("France (European Territory)", "FX");
            put("Gabon", "GA");
            put("Great Britain", "UK");
            put("Grenada", "GD");
            put("Georgia", "GE");
            put("French Guyana", "GF");
            put("Ghana", "GH");
            put("Gibraltar", "GI");
            put("Greenland", "GL");
            put("Gambia", "GM");
            put("Guinea", "GN");
            put("Guadeloupe (French)", "GP");
            put("Equatorial Guinea", "GQ");
            put("Greece", "GR");
            put("S. Georgia & S. Sandwich Isls.", "GS");
            put("Guatemala", "GT");
            put("Guam (USA)", "GU");
            put("Guinea Bissau", "GW");
            put("Guyana", "GY");
            put("Hong Kong", "HK");
            put("Heard And McDonald Islands", "HM");
            put("Honduras", "HN");
            put("Croatia", "HR");
            put("Haiti", "HT");
            put("Hungary", "HU");
            put("Indonesia", "ID");
            put("Ireland", "IE");
            put("Israel", "IL");
            put("India", "IN");
            put("British Indian Ocean Territory", "IO");
            put("Iraq", "IQ");
            put("Iran", "IR");
            put("Iceland", "IS");
            put("Italy", "IT");
            put("Jamaica", "JM");
            put("Jordan", "JO");
            put("Japan", "JP");
            put("Kenya", "KE");
            put("Kyrgyz Republic (Kyrgyzstan)", "KG");
            put("Cambodia, Kingdom Of", "KH");
            put("Kiribati", "KI");
            put("Comoros", "KM");
            put("Saint Kitts & Nevis Anguilla", "KN");
            put("North Korea", "KP");
            put("South Korea", "KR");
            put("Kuwait", "KW");
            put("Cayman Islands", "KY");
            put("Kazakhstan", "KZ");
            put("Laos", "LA");
            put("Lebanon", "LB");
            put("Saint Lucia", "LC");
            put("Liechtenstein", "LI");
            put("Sri Lanka", "LK");
            put("Liberia", "LR");
            put("Lesotho", "LS");
            put("Lithuania", "LT");
            put("Luxembourg", "LU");
            put("Latvia", "LV");
            put("Libya", "LY");
            put("Morocco", "MA");
            put("Monaco", "MC");
            put("Moldavia", "MD");
            put("Madagascar", "MG");
            put("Marshall Islands", "MH");
            put("Macedonia", "MK");
            put("Mali", "ML");
            put("Myanmar", "MM");
            put("Mongolia", "MN");
            put("Macau", "MO");
            put("Northern Mariana Islands", "MP");
            put("Martinique (French)", "MQ");
            put("Mauritania", "MR");
            put("Montserrat", "MS");
            put("Malta", "MT");
            put("Mauritius", "MU");
            put("Maldives", "MV");
            put("Malawi", "MW");
            put("Mexico", "MX");
            put("Malaysia", "MY");
            put("Mozambique", "MZ");
            put("Namibia", "NA");
            put("New Caledonia (French)", "NC");
            put("Niger", "NE");
            put("Norfolk Island", "NF");
            put("Nigeria", "NG");
            put("Nicaragua", "NI");
            put("Netherlands", "NL");
            put("Norway", "NO");
            put("Nepal", "NP");
            put("Nauru", "NR");
            put("Neutral Zone", "NT");
            put("Niue", "NU");
            put("New Zealand", "NZ");
            put("Oman", "OM");
            put("Panama", "PA");
            put("Peru", "PE");
            put("Polynesia (French)", "PF");
            put("Papua New Guinea", "PG");
            put("Philippines", "PH");
            put("Pakistan", "PK");
            put("Poland", "PL");
            put("Saint Pierre And Miquelon", "PM");
            put("Pitcairn Island", "PN");
            put("Puerto Rico", "PR");
            put("Portugal", "PT");
            put("Palau", "PW");
            put("Paraguay", "PY");
            put("Qatar", "QA");
            put("Reunion (French)", "RE");
            put("Romania", "RO");
            put("Russian Federation", "RU");
            put("Rwanda", "RW");
            put("Saudi Arabia", "SA");
            put("Solomon Islands", "SB");
            put("Seychelles", "SC");
            put("Sudan", "SD");
            put("Sweden", "SE");
            put("Singapore", "SG");
            put("Saint Helena", "SH");
            put("Slovenia", "SI");
            put("Svalbard And Jan Mayen Islands", "SJ");
            put("Slovak Republic", "SK");
            put("Sierra Leone", "SL");
            put("San Marino", "SM");
            put("Senegal", "SN");
            put("Somalia", "SO");
            put("Serbia", "RS");
            put("Suriname", "SR");
            put("Saint Tome (Sao Tome) And Principe", "ST");
            put("Former USSR", "SU");
            put("El Salvador", "SV");
            put("Syria", "SY");
            put("Swaziland", "SZ");
            put("Turks And Caicos Islands", "TC");
            put("Chad", "TD");
            put("French Southern Territories", "TF");
            put("Togo", "TG");
            put("Thailand", "TH");
            put("Tadjikistan", "TJ");
            put("Tokelau", "TK");
            put("Turkmenistan", "TM");
            put("Tunisia", "TN");
            put("Tonga", "TO");
            put("East Timor", "TP");
            put("Turkey", "TR");
            put("Trinidad And Tobago", "TT");
            put("Tuvalu", "TV");
            put("Taiwan", "TW");
            put("Tanzania", "TZ");
            put("Ukraine", "UA");
            put("Uganda", "UG");
            put("United Kingdom", "UK");
            put("USA Minor Outlying Islands", "UM");
            put("United States", "US");
            put("Uruguay", "UY");
            put("Uzbekistan", "UZ");
            put("Holy See (Vatican City State)", "VA");
            put("Saint Vincent & Grenadines", "VC");
            put("Venezuela", "VE");
            put("Virgin Islands (British)", "VG");
            put("Virgin Islands (USA)", "VI");
            put("Vietnam", "VN");
            put("Vanuatu", "VU");
            put("Wallis And Futuna Islands", "WF");
            put("Samoa", "WS");
            put("Yemen", "YE");
            put("Mayotte", "YT");
            put("South Africa", "ZA");
            put("Zambia", "ZM");
            put("Zaire", "ZR");
            put("Zimbabwe", "ZW");
        }
    };

    public static final List<String> listOfWorldCountryCodes = new ArrayList<>(mapOfWorldStates.keySet());
    public static final List<String> listofWorldCountryNames = new ArrayList<>(mapOfWorldStates.values());

}

